DATASET:
  CHUNK_LENGTH: 15
  DATA_PATH: data/ibm_debater/full
  LOADER:
    BATCH_SIZE: 8
    DROP_LAST: false
    NUM_WORKERS: 4
  LOAD_AUDIO: true
  LOAD_MOTION: false
  LOAD_TEXT: true
  SAMPLE_CUT_TYPE: first
  SMALL_VERSION: false
  TOKENIZER: distilbert-base-uncased
MODEL:
  AUDIO:
    CLASSIFY: false
    DROPOUT_VALUES:
    - 0.3
    - 0.3
    N_TRAINABLE_LAYERS: 4
    N_TRANSFORMERS: 4
    PRE_CLASSIFIER: true
  MULTIMODAL:
    AUDIO_CHECKPOINT_PATH: ''
    CROSS:
      POOL: avg
      TYPE: audio2text
      USE: true
    DROPOUT_VALUES:
    - 0.3
    FREEZE_AUDIO: false
    FREEZE_TEXT: false
    LOAD_AUDIO_CHECKPOINT: false
    LOAD_TEXT_CHECKPOINT: false
    TEXT_CHECKPOINT_PATH: ''
  NAME: multimodal
  TEXT:
    CLASSIFY: false
    DISTILBERT: distilbert-base-uncased
    DROPOUT_VALUES:
    - 0.3
    - 0.3
    N_TRAINABLE_LAYERS: 2
    PRE_CLASSIFIER: true
  TEXT_GENERATION:
    BART_DECODER_CLS_N_TRAINABLE_LAYERS: 6
    BART_DECODER_GEN_N_TRAINABLE_LAYERS: 6
    BART_ENCODER_N_TRAINABLE_LAYERS: 6
    CROSS_ATTN_N_LAYERS: 0
    DROPOUT_VALUE: 0.3
    WAV2VEC2_N_TRAINABLE_LAYERS: 12
    WAV2VEC2_N_TRANSFORMERS: 12
SETTINGS:
  DEVICE: cuda
TRAIN:
  CHECKPOINT_PATH: ''
  EARLY_STOPPING:
    PATIENCE: 3
  EPOCHS: 20
  GENERATION_METRICS:
  - bleu
  - rouge
  LR: 2.0e-05
  LR_SCHEDULER: {}
  OPTIMIZER: adam
  OPTIMIZER_ARGS: {}
  SAVE_CHECKPOINT: false
