DATASET:
  CHUNK_LENGTH: 15
  DATA_PATH: data/ibm_debater/full
  LOADER:
    BATCH_SIZE: 16
    DROP_LAST: true
    NUM_WORKERS: 0
  LOAD_AUDIO: false
  LOAD_TEXT: true
  SMALL_VERSION: false
  TOKENIZER: distilbert-base-uncased
MODEL:
  NAME: text
  TEXT:
    CLASSIFY: true
    DISTILBERT: distilbert-base-uncased
    DROPOUT_VALUES:
    - 0.3
    - 0.3
    N_TRAINABLE_LAYERS: 2
    PRE_CLASSIFIER: true
SETTINGS:
  DEVICE: cuda
TRAIN:
  CHECKPOINT_PATH: ''
  EARLY_STOPPING:
    PATIENCE: 3
  EPOCHS: 20
  LR: 2.0e-05
  LR_SCHEDULER: {}
  OPTIMIZER: adam
  OPTIMIZER_ARGS: {}
  SAVE_CHECKPOINT: false
