DATASET:
  CHUNK_LENGTH: 10
  DATA_PATH: data/ibm_debater/full
  LOADER:
    BATCH_SIZE: 1
    DROP_LAST: false
    NUM_WORKERS: 0
  LOAD_AUDIO: false
  LOAD_TEXT: true
  LOAD_MOTION: true
  SAMPLE_CUT_TYPE: last
  SMALL_VERSION: false
  TOKENIZER: distilbert-base-uncased
MODEL:
  NAME: text
  TEXT:
    CLASSIFY: true
    DISTILBERT: distilbert-base-uncased
    DROPOUT_VALUES:
    - 0.3
    - 0.3
    N_TRAINABLE_LAYERS: 2
    PRE_CLASSIFIER: true
SETTINGS:
  DEVICE: cuda
TRAIN:
  CHECKPOINT_PATH: 'checkpoints/bart_mult.pkl'
  EARLY_STOPPING:
    PATIENCE: 3
  EPOCHS: 30
  LR: 2.0e-03
  LR_SCHEDULER: {}
  OPTIMIZER: adam
  OPTIMIZER_ARGS: {}
  SAVE_CHECKPOINT: true
